credentials        = "~/keys/polaris-test-keyfile.json"
project_id         = "cloud-native-data"
region             = "europe-west2"
zones              = ["europe-west2-a", "europe-west2-b", "europe-west2-c"]
name               = "polaris-test-09"
machine_type       = "n1-standard-2"
min_count          = 1
max_count          = 3
disk_size_gb       = 100
initial_node_count = 1
service_account    = "polaris-test@cloud-native-data.iam.gserviceaccount.com"
#node_pool_default_meta = "polaris-test-nodepool"
