name               = "polaris-test-10"
project_id         = "cloud-native-data"
region             = "asia-northeast3"
zones              = ["asia-northeast3-a", "asia-northeast3-b", "asia-northeast3-c"]
machine_type       = "n1-standard-2"
min_count          = 1
max_count          = 3
disk_size_gb       = 100
initial_node_count = 1
service_account    = "polaris-test@cloud-native-data.iam.gserviceaccount.com"
#node_pool_default_meta = "polaris-test-nodepool"
credentials        = "~/keys/polaris-test-keyfile.json"
