name               = "polaris-test-02"
project_id         = "cloud-native-data"
region             = "us-east4"
zones              = ["us-east4-a", "us-east4-b", "us-east4-c"]
machine_type       = "n1-standard-2"
min_count          = 1
max_count          = 3
disk_size_gb       = 100
initial_node_count = 1
service_account    = "polaris-test@cloud-native-data.iam.gserviceaccount.com"
#node_pool_default_meta = "polaris-test-nodepool"
credentials        = "~/keys/polaris-test-keyfile.json"
